// Generated by scripts/generate-csharp-components.py. Do not edit by hand.
using System.Numerics;
namespace Canis;

public sealed class AnimationPlayer : NativeComponent
{
    public bool Playing { get => GetField<bool>("playing"); set => SetField("playing", value); }
    public bool Loop { get => GetField<bool>("loop"); set => SetField("loop", value); }
    public float Speed { get => GetField<float>("speed"); set => SetField("speed", value); }
    public float Time { get => GetField<float>("time"); set => SetField("time", value); }
}

public sealed class Animator : NativeComponent
{
    public bool Playing { get => GetField<bool>("playing"); set => SetField("playing", value); }
}

public sealed class BlockoutShape : NativeComponent
{
    public bool Active { get => GetField<bool>("active"); set => SetField("active", value); }
    public int Type { get => GetField<int>("type"); set => SetField("type", value); }
    public Vector3 Size { get => GetField<Vector3>("size"); set => SetField("size", value); }
    public int Sides { get => GetField<int>("sides"); set => SetField("sides", value); }
    public int StepCount { get => GetField<int>("stepCount"); set => SetField("stepCount", value); }
    public Vector2 UvScale { get => GetField<Vector2>("uvScale"); set => SetField("uvScale", value); }
    public int LoopCutsX { get => GetField<int>("loopCutsX"); set => SetField("loopCutsX", value); }
    public int LoopCutsY { get => GetField<int>("loopCutsY"); set => SetField("loopCutsY", value); }
    public int LoopCutsZ { get => GetField<int>("loopCutsZ"); set => SetField("loopCutsZ", value); }
    public Vector3 ExtrudeNegative { get => GetField<Vector3>("extrudeNegative"); set => SetField("extrudeNegative", value); }
    public Vector3 ExtrudePositive { get => GetField<Vector3>("extrudePositive"); set => SetField("extrudePositive", value); }
    public bool GenerateCollision { get => GetField<bool>("generateCollision"); set => SetField("generateCollision", value); }
    public bool MeshEdited { get => GetField<bool>("meshEdited"); set => SetField("meshEdited", value); }
    public bool VisibleInGame { get => GetField<bool>("visibleInGame"); set => SetField("visibleInGame", value); }
    public bool CastShadow { get => GetField<bool>("castShadow"); set => SetField("castShadow", value); }
}

public sealed class BoneAttachment : NativeComponent
{
}

public sealed class BoxCollider : NativeComponent
{
    public bool Active { get => GetField<bool>("active"); set => SetField("active", value); }
    public Vector3 Offset { get => GetField<Vector3>("offset"); set => SetField("offset", value); }
    public Vector3 Size { get => GetField<Vector3>("size"); set => SetField("size", value); }
}

public sealed class Camera : NativeComponent
{
    public bool Primary { get => GetField<bool>("primary"); set => SetField("primary", value); }
    public float FovDegrees { get => GetField<float>("fovDegrees"); set => SetField("fovDegrees", value); }
    public float NearClip { get => GetField<float>("nearClip"); set => SetField("nearClip", value); }
    public float FarClip { get => GetField<float>("farClip"); set => SetField("farClip", value); }
}

public sealed class Camera2D : NativeComponent
{
}

public sealed class Canvas : NativeComponent
{
}

public sealed class CapsuleCollider : NativeComponent
{
    public bool Active { get => GetField<bool>("active"); set => SetField("active", value); }
    public Vector3 Offset { get => GetField<Vector3>("offset"); set => SetField("offset", value); }
    public float HalfHeight { get => GetField<float>("halfHeight"); set => SetField("halfHeight", value); }
    public float Radius { get => GetField<float>("radius"); set => SetField("radius", value); }
}

public sealed class CloudNavSurface : NativeComponent
{
    public bool Active { get => GetField<bool>("active"); set => SetField("active", value); }
    public bool BuildOnReady { get => GetField<bool>("buildOnReady"); set => SetField("buildOnReady", value); }
    public bool ShowDebug { get => GetField<bool>("showDebug"); set => SetField("showDebug", value); }
    public Vector3 Size { get => GetField<Vector3>("size"); set => SetField("size", value); }
    public float NodeSpacing { get => GetField<float>("nodeSpacing"); set => SetField("nodeSpacing", value); }
    public float AgentRadius { get => GetField<float>("agentRadius"); set => SetField("agentRadius", value); }
}

public sealed class ConvexMeshCollider : NativeComponent
{
    public bool Active { get => GetField<bool>("active"); set => SetField("active", value); }
    public bool UseAttachedModel { get => GetField<bool>("useAttachedModel"); set => SetField("useAttachedModel", value); }
    public Vector3 Offset { get => GetField<Vector3>("offset"); set => SetField("offset", value); }
    public Vector3 Scale { get => GetField<Vector3>("scale"); set => SetField("scale", value); }
    public float ConvexRadius { get => GetField<float>("convexRadius"); set => SetField("convexRadius", value); }
    public string ModelPath { get => GetField<string>("modelPath"); set => SetField("modelPath", value); }
}

public sealed class DirectionalLight : NativeComponent
{
    public bool Enabled { get => GetField<bool>("enabled"); set => SetField("enabled", value); }
    public Vector4 Color { get => GetField<Vector4>("color"); set => SetField("color", value); }
    public float Intensity { get => GetField<float>("intensity"); set => SetField("intensity", value); }
    public Vector3 Direction { get => GetField<Vector3>("direction"); set => SetField("direction", value); }
}

public sealed class Material : NativeComponent
{
    public Vector4 Color { get => GetField<Vector4>("color"); set => SetField("color", value); }
}

public sealed class MeshCollider : NativeComponent
{
    public bool Active { get => GetField<bool>("active"); set => SetField("active", value); }
    public bool UseAttachedModel { get => GetField<bool>("useAttachedModel"); set => SetField("useAttachedModel", value); }
    public string ModelPath { get => GetField<string>("modelPath"); set => SetField("modelPath", value); }
}

public sealed class ModelAnimation : NativeComponent
{
    public bool PlayAnimation { get => GetField<bool>("playAnimation"); set => SetField("playAnimation", value); }
    public bool Loop { get => GetField<bool>("loop"); set => SetField("loop", value); }
    public float AnimationSpeed { get => GetField<float>("animationSpeed"); set => SetField("animationSpeed", value); }
    public float AnimationTime { get => GetField<float>("animationTime"); set => SetField("animationTime", value); }
    public Vector3 RootMotionMask { get => GetField<Vector3>("rootMotionMask"); set => SetField("rootMotionMask", value); }
}

public sealed class NavMeshSurface : NativeComponent
{
    public bool Active { get => GetField<bool>("active"); set => SetField("active", value); }
    public bool BuildOnReady { get => GetField<bool>("buildOnReady"); set => SetField("buildOnReady", value); }
    public bool ShowDebug { get => GetField<bool>("showDebug"); set => SetField("showDebug", value); }
    public bool MeshCollidersOnly { get => GetField<bool>("meshCollidersOnly"); set => SetField("meshCollidersOnly", value); }
    public Vector3 Size { get => GetField<Vector3>("size"); set => SetField("size", value); }
    public float CellSize { get => GetField<float>("cellSize"); set => SetField("cellSize", value); }
    public float AgentRadius { get => GetField<float>("agentRadius"); set => SetField("agentRadius", value); }
    public float AgentHeight { get => GetField<float>("agentHeight"); set => SetField("agentHeight", value); }
    public float MaxFloorDelta { get => GetField<float>("maxFloorDelta"); set => SetField("maxFloorDelta", value); }
}

public sealed class NetworkIdentity : NativeComponent
{
    public bool ServerOwned { get => GetField<bool>("serverOwned"); set => SetField("serverOwned", value); }
    public bool LocalOwned { get => GetField<bool>("localOwned"); set => SetField("localOwned", value); }
    public bool ReplicateTransform { get => GetField<bool>("replicateTransform"); set => SetField("replicateTransform", value); }
}

public sealed class ParticleEmitter : NativeComponent
{
}

public sealed class PointLight : NativeComponent
{
    public bool Enabled { get => GetField<bool>("enabled"); set => SetField("enabled", value); }
    public Vector4 Color { get => GetField<Vector4>("color"); set => SetField("color", value); }
    public float Intensity { get => GetField<float>("intensity"); set => SetField("intensity", value); }
    public float Range { get => GetField<float>("range"); set => SetField("range", value); }
}

public sealed class PrefabInstance : NativeComponent
{
}

public sealed class RectTransform : NativeComponent
{
}

public sealed class Rigidbody : NativeComponent
{
    public bool Active { get => GetField<bool>("active"); set => SetField("active", value); }
    public int MotionType { get => GetField<int>("motionType"); set => SetField("motionType", value); }
    public float Mass { get => GetField<float>("mass"); set => SetField("mass", value); }
    public float Friction { get => GetField<float>("friction"); set => SetField("friction", value); }
    public float Restitution { get => GetField<float>("restitution"); set => SetField("restitution", value); }
    public float LinearDamping { get => GetField<float>("linearDamping"); set => SetField("linearDamping", value); }
    public float AngularDamping { get => GetField<float>("angularDamping"); set => SetField("angularDamping", value); }
    public bool UseGravity { get => GetField<bool>("useGravity"); set => SetField("useGravity", value); }
    public float GravityFactor { get => GetField<float>("gravityFactor"); set => SetField("gravityFactor", value); }
    public bool IsSensor { get => GetField<bool>("isSensor"); set => SetField("isSensor", value); }
    public bool AllowSleeping { get => GetField<bool>("allowSleeping"); set => SetField("allowSleeping", value); }
    public bool LockRotationX { get => GetField<bool>("lockRotationX"); set => SetField("lockRotationX", value); }
    public bool LockRotationY { get => GetField<bool>("lockRotationY"); set => SetField("lockRotationY", value); }
    public bool LockRotationZ { get => GetField<bool>("lockRotationZ"); set => SetField("lockRotationZ", value); }
    public Vector3 LinearVelocity { get => GetField<Vector3>("linearVelocity"); set => SetField("linearVelocity", value); }
    public Vector3 AngularVelocity { get => GetField<Vector3>("angularVelocity"); set => SetField("angularVelocity", value); }
}

public sealed class SphereCollider : NativeComponent
{
    public bool Active { get => GetField<bool>("active"); set => SetField("active", value); }
    public Vector3 Offset { get => GetField<Vector3>("offset"); set => SetField("offset", value); }
    public float Radius { get => GetField<float>("radius"); set => SetField("radius", value); }
}

public sealed class Sprite2D : NativeComponent
{
    public Vector4 Color { get => GetField<Vector4>("color"); set => SetField("color", value); }
    public Vector4 Uv { get => GetField<Vector4>("uv"); set => SetField("uv", value); }
    public bool FlipX { get => GetField<bool>("flipX"); set => SetField("flipX", value); }
    public bool FlipY { get => GetField<bool>("flipY"); set => SetField("flipY", value); }
}

public sealed class SpriteAnimation : NativeComponent
{
}

public sealed class Terrain : NativeComponent
{
}

public sealed class UIButton : NativeComponent
{
    public bool Active { get => GetField<bool>("active"); set => SetField("active", value); }
    public string TargetScript { get => GetField<string>("targetScript"); set => SetField("targetScript", value); }
    public string ActionName { get => GetField<string>("actionName"); set => SetField("actionName", value); }
    public Vector4 HoverColor { get => GetField<Vector4>("hoverColor"); set => SetField("hoverColor", value); }
    public Vector4 PressedColor { get => GetField<Vector4>("pressedColor"); set => SetField("pressedColor", value); }
    public float HoverScale { get => GetField<float>("hoverScale"); set => SetField("hoverScale", value); }
    public float PressedScale { get => GetField<float>("pressedScale"); set => SetField("pressedScale", value); }
}

public sealed class UIDragSource : NativeComponent
{
    public bool Active { get => GetField<bool>("active"); set => SetField("active", value); }
    public string PayloadType { get => GetField<string>("payloadType"); set => SetField("payloadType", value); }
    public string PayloadValue { get => GetField<string>("payloadValue"); set => SetField("payloadValue", value); }
}

public sealed class UIDropTarget : NativeComponent
{
    public bool Active { get => GetField<bool>("active"); set => SetField("active", value); }
    public string TargetScript { get => GetField<string>("targetScript"); set => SetField("targetScript", value); }
    public string ActionName { get => GetField<string>("actionName"); set => SetField("actionName", value); }
    public string AcceptedPayloadType { get => GetField<string>("acceptedPayloadType"); set => SetField("acceptedPayloadType", value); }
    public Vector4 BaseColor { get => GetField<Vector4>("baseColor"); set => SetField("baseColor", value); }
    public Vector4 HoverColor { get => GetField<Vector4>("hoverColor"); set => SetField("hoverColor", value); }
}

public sealed class UIInputField : NativeComponent
{
    public bool Active { get => GetField<bool>("active"); set => SetField("active", value); }
    public string TargetScript { get => GetField<string>("targetScript"); set => SetField("targetScript", value); }
    public string TargetProperty { get => GetField<string>("targetProperty"); set => SetField("targetProperty", value); }
    public string Text { get => GetField<string>("text"); set => SetField("text", value); }
    public string Placeholder { get => GetField<string>("placeholder"); set => SetField("placeholder", value); }
    public string AllowedCharacters { get => GetField<string>("allowedCharacters"); set => SetField("allowedCharacters", value); }
    public int MaxLength { get => GetField<int>("maxLength"); set => SetField("maxLength", value); }
    public Vector4 HoverColor { get => GetField<Vector4>("hoverColor"); set => SetField("hoverColor", value); }
    public Vector4 FocusedColor { get => GetField<Vector4>("focusedColor"); set => SetField("focusedColor", value); }
    public Vector4 TextColor { get => GetField<Vector4>("textColor"); set => SetField("textColor", value); }
    public Vector4 PlaceholderColor { get => GetField<Vector4>("placeholderColor"); set => SetField("placeholderColor", value); }
}
