if(CANIS_PLATFORM_WEB)
    include("${CMAKE_CURRENT_LIST_DIR}/CSharpWeb.cmake")
    return()
endif()
if(ANDROID)
    message(FATAL_ERROR "CANIS_ENABLE_CSHARP currently requires a desktop build")
endif()
if(NOT CMAKE_SIZEOF_VOID_P EQUAL 8)
    message(FATAL_ERROR "The experimental C# host currently requires a 64-bit desktop build")
endif()
find_program(CANIS_DOTNET_EXECUTABLE dotnet REQUIRED)
get_filename_component(_canis_dotnet_real "${CANIS_DOTNET_EXECUTABLE}" REALPATH)
get_filename_component(_canis_dotnet_root "${_canis_dotnet_real}" DIRECTORY)
set(CANIS_DOTNET_ROOT "${_canis_dotnet_root}" CACHE PATH "Root of the .NET 10 installation")
file(GLOB _canis_host_headers "${CANIS_DOTNET_ROOT}/packs/Microsoft.NETCore.App.Host.*/10.*/runtimes/*/native/hostfxr.h")
file(GLOB _canis_hostfxr "${CANIS_DOTNET_ROOT}/host/fxr/10.*/${CMAKE_SHARED_LIBRARY_PREFIX}hostfxr${CMAKE_SHARED_LIBRARY_SUFFIX}")
if(NOT _canis_host_headers OR NOT _canis_hostfxr)
    message(FATAL_ERROR "C# requires the .NET 10 SDK and native host pack; set CANIS_DOTNET_ROOT if necessary")
endif()
list(SORT _canis_host_headers COMPARE NATURAL ORDER DESCENDING)
list(SORT _canis_hostfxr COMPARE NATURAL ORDER DESCENDING)
list(GET _canis_host_headers 0 _canis_host_header)
list(GET _canis_hostfxr 0 CANIS_HOSTFXR_PATH)
get_filename_component(_canis_host_include "${_canis_host_header}" DIRECTORY)
set(CANIS_MANAGED_HOST_DIR "${CMAKE_BINARY_DIR}/managed/host")
file(GLOB_RECURSE _canis_managed_sources CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/managed/*.cs" "${CMAKE_CURRENT_SOURCE_DIR}/managed/*.csproj")
list(FILTER _canis_managed_sources EXCLUDE REGEX "/(obj|bin)/")
add_custom_command(OUTPUT "${CANIS_MANAGED_HOST_DIR}/Canis.ManagedHost.dll" "${CANIS_MANAGED_HOST_DIR}/Canis.Core.dll" "${CANIS_MANAGED_HOST_DIR}/Canis.ManagedHost.runtimeconfig.json"
    COMMAND "${CANIS_DOTNET_EXECUTABLE}" build "${CMAKE_CURRENT_SOURCE_DIR}/managed/Canis.ManagedHost/Canis.ManagedHost.csproj"
        --output "${CANIS_MANAGED_HOST_DIR}" --artifacts-path "${CMAKE_BINARY_DIR}/managed/artifacts" --nologo
    DEPENDS ${_canis_managed_sources} VERBATIM)
add_custom_target(CanisManagedHost DEPENDS "${CANIS_MANAGED_HOST_DIR}/Canis.ManagedHost.dll")
add_dependencies(${CANIS_ENGINE_LIB} CanisManagedHost)
target_include_directories(${CANIS_ENGINE_LIB} PRIVATE "${_canis_host_include}")
target_compile_definitions(${CANIS_ENGINE_LIB} PRIVATE
    CANIS_DOTNET_EXECUTABLE="${CANIS_DOTNET_EXECUTABLE}"
    CANIS_MANAGED_HOST_DIR="${CANIS_MANAGED_HOST_DIR}"
    CANIS_HOSTFXR_PATH="${CANIS_HOSTFXR_PATH}")
if(BUILD_TESTING)
    add_executable(CanisCSharpComponentsTests tests/CSharpComponentsTests.cpp)
    target_link_libraries(CanisCSharpComponentsTests PRIVATE ${CANIS_ENGINE_LIB} SDL3::SDL3)
    add_test(NAME CanisCSharpComponentsTests COMMAND CanisCSharpComponentsTests)
    set_tests_properties(CanisCSharpComponentsTests PROPERTIES TIMEOUT 120)
    add_executable(CanisCSharpRuntimeTests tests/CSharpRuntimeTests.cpp)
    target_link_libraries(CanisCSharpRuntimeTests PRIVATE ${CANIS_ENGINE_LIB} SDL3::SDL3)
    add_test(NAME CanisCSharpRuntimeTests COMMAND CanisCSharpRuntimeTests)
    set_tests_properties(CanisCSharpRuntimeTests PROPERTIES TIMEOUT 120)
endif()
if(CANIS_ENABLE_EDITOR)
    file(GLOB _canis_language_sources CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/managed/Canis.LanguageTools/*.cs" "${CMAKE_CURRENT_SOURCE_DIR}/managed/Canis.LanguageTools/*.csproj")
    add_custom_command(OUTPUT "${CMAKE_BINARY_DIR}/managed/tools/Canis.LanguageTools.dll"
        COMMAND "${CANIS_DOTNET_EXECUTABLE}" build "${CMAKE_CURRENT_SOURCE_DIR}/managed/Canis.LanguageTools/Canis.LanguageTools.csproj"
            --output "${CMAKE_BINARY_DIR}/managed/tools" --artifacts-path "${CMAKE_BINARY_DIR}/managed/language-artifacts" --nologo
        DEPENDS ${_canis_language_sources} VERBATIM)
    add_custom_target(CanisLanguageTools DEPENDS "${CMAKE_BINARY_DIR}/managed/tools/Canis.LanguageTools.dll")
    add_dependencies(${CANIS_ENGINE_LIB} CanisLanguageTools)
    if(BUILD_TESTING)
        find_package(Python3 COMPONENTS Interpreter REQUIRED)
        add_test(NAME CanisCSharpLanguageTests COMMAND "${Python3_EXECUTABLE}" "${CMAKE_CURRENT_SOURCE_DIR}/tests/CSharpLanguageTests.py" "${CMAKE_BINARY_DIR}/managed/tools/Canis.LanguageTools.dll" "${CANIS_MANAGED_HOST_DIR}/Canis.Core.dll")
    endif()
endif()
target_compile_definitions(${CANIS_ENGINE_LIB} PRIVATE CANIS_LANGUAGE_TOOLS_PATH="${CMAKE_BINARY_DIR}/managed/tools/Canis.LanguageTools.dll")
