option(CANIS_ENABLE_OPENXR "Build desktop OpenXR headset support" OFF)
if(CANIS_ENABLE_OPENXR)
    if(CANIS_PLATFORM_WEB OR ANDROID OR APPLE OR NOT (WIN32 OR CMAKE_SYSTEM_NAME STREQUAL "Linux"))
        message(FATAL_ERROR "The OpenXR backend currently supports Windows OpenGL and Linux X11/GLX. Android/GLES, Vulkan and web XR need separate backends.")
    endif()
    find_package(OpenXR CONFIG REQUIRED)
    target_link_libraries(CanisEngine PRIVATE OpenXR::openxr_loader)
    target_compile_definitions(CanisEngine PRIVATE CANIS_OPENXR=1)
    if(WIN32)
        target_link_libraries(CanisEngine PRIVATE opengl32)
    else()
        find_package(OpenGL REQUIRED)
        find_package(X11 REQUIRED)
        target_link_libraries(CanisEngine PRIVATE OpenGL::GL X11::X11)
    endif()
else()
    target_compile_definitions(CanisEngine PRIVATE CANIS_OPENXR=0)
endif()
if(BUILD_TESTING AND NOT CANIS_PLATFORM_WEB)
    add_executable(CanisVRMathTests tests/VRMathTests.cpp)
    target_include_directories(CanisVRMathTests PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/include")
    target_link_libraries(CanisVRMathTests PRIVATE glm)
    add_test(NAME CanisVRMathTests COMMAND CanisVRMathTests)
endif()
if(BUILD_TESTING AND NOT CANIS_PLATFORM_WEB)
    add_executable(CanisVRSystemTests tests/VRSystemTests.cpp)
    target_link_libraries(CanisVRSystemTests PRIVATE CanisEngine libglew_static)
    if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
        find_program(CANIS_XVFB_RUN xvfb-run)
        if(CANIS_XVFB_RUN)
            add_test(NAME CanisVRSystemTests COMMAND "${CANIS_XVFB_RUN}" -a $<TARGET_FILE:CanisVRSystemTests>)
        endif()
    else()
        add_test(NAME CanisVRSystemTests COMMAND CanisVRSystemTests)
    endif()
endif()
# ELF symbol interposition lets this test exercise the real backend against a
# strict API test double. It does not replace runtime validation on hardware.
if(BUILD_TESTING AND CANIS_ENABLE_OPENXR AND CMAKE_SYSTEM_NAME STREQUAL "Linux" AND CANIS_XVFB_RUN)
    add_executable(CanisVRNativeTests tests/VRNativeTests.cpp)
    target_link_libraries(CanisVRNativeTests PRIVATE CanisEngine libglew_static OpenXR::openxr_loader)
    set_target_properties(CanisVRNativeTests PROPERTIES ENABLE_EXPORTS ON)
    add_test(NAME CanisVRNativeTests COMMAND "${CANIS_XVFB_RUN}" -a $<TARGET_FILE:CanisVRNativeTests>)
endif()
if(BUILD_TESTING AND NOT CANIS_PLATFORM_WEB)
    add_executable(CanisVRComfortTests tests/VRComfortTests.cpp src/VR/PlayerSettings.cpp)
    target_include_directories(CanisVRComfortTests PRIVATE "${CMAKE_CURRENT_SOURCE_DIR}/include")
    target_link_libraries(CanisVRComfortTests PRIVATE glm yaml-cpp)
    add_test(NAME CanisVRComfortTests COMMAND CanisVRComfortTests)
endif()
