# Valve Steam Audio C SDK, pinned for reproducible builds. SDL remains the audio device backend.
option(CANIS_ENABLE_STEAM_AUDIO "Use Steam Audio HRTF spatialization" ON)
set(CANIS_STEAM_AUDIO_ROOT "" CACHE PATH "Existing extracted Steam Audio SDK (contains include/phonon.h)")
if(CANIS_PLATFORM_WEB)
    set(CANIS_ENABLE_STEAM_AUDIO OFF)
endif()
if(CANIS_ENABLE_STEAM_AUDIO)
    if(NOT CANIS_STEAM_AUDIO_ROOT)
        include(FetchContent)
        FetchContent_Declare(canis_steam_audio
            URL https://github.com/ValveSoftware/steam-audio/releases/download/v4.8.1/steamaudio_4.8.1.zip
            URL_HASH SHA256=4a0aa5ec1176f38f0b0993a37c2259d9e86f27e22d5e24f83ec4c3cb9a1d5449
            DOWNLOAD_EXTRACT_TIMESTAMP TRUE)
        FetchContent_MakeAvailable(canis_steam_audio)
        set(CANIS_STEAM_AUDIO_ROOT "${canis_steam_audio_SOURCE_DIR}")
        if(EXISTS "${CANIS_STEAM_AUDIO_ROOT}/steamaudio/include/phonon.h")
            string(APPEND CANIS_STEAM_AUDIO_ROOT "/steamaudio")
        endif()
    endif()
    if(WIN32 AND CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(_steam_lib "${CANIS_STEAM_AUDIO_ROOT}/lib/windows-x64/phonon.dll")
        set(_steam_import "${CANIS_STEAM_AUDIO_ROOT}/lib/windows-x64/phonon.lib")
    elseif(APPLE)
        set(_steam_lib "${CANIS_STEAM_AUDIO_ROOT}/lib/osx/libphonon.dylib")
    elseif(CMAKE_SYSTEM_NAME STREQUAL "Linux" AND CMAKE_SYSTEM_PROCESSOR MATCHES "^(x86_64|AMD64|amd64)$")
        set(_steam_lib "${CANIS_STEAM_AUDIO_ROOT}/lib/linux-x64/libphonon.so")
    else()
        message(FATAL_ERROR "Steam Audio SDK platform not configured. Set CANIS_ENABLE_STEAM_AUDIO=OFF for stereo spatial panning.")
    endif()
    if(NOT EXISTS "${_steam_lib}" OR NOT EXISTS "${CANIS_STEAM_AUDIO_ROOT}/include/phonon.h")
        message(FATAL_ERROR "Invalid CANIS_STEAM_AUDIO_ROOT: ${CANIS_STEAM_AUDIO_ROOT}")
    endif()
    add_library(CanisSteamAudio SHARED IMPORTED)
    set_target_properties(CanisSteamAudio PROPERTIES IMPORTED_LOCATION "${_steam_lib}"
        INTERFACE_INCLUDE_DIRECTORIES "${CANIS_STEAM_AUDIO_ROOT}/include")
    if(WIN32)
        set_target_properties(CanisSteamAudio PROPERTIES IMPORTED_IMPLIB "${_steam_import}")
    endif()
    target_link_libraries(CanisEngine PRIVATE CanisSteamAudio)
    if(APPLE)
        set(_steam_origin "@loader_path")
    else()
        set(_steam_origin "$ORIGIN")
    endif()
    set_property(TARGET CanisEngine APPEND PROPERTY BUILD_RPATH "${_steam_origin}")
    set_property(TARGET CanisEngine APPEND PROPERTY INSTALL_RPATH "${_steam_origin}")
    add_custom_command(TARGET CanisEngine POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy_if_different "${_steam_lib}" "$<TARGET_FILE_DIR:CanisEngine>"
        COMMAND ${CMAKE_COMMAND} -E make_directory "$<TARGET_FILE_DIR:CanisEngine>/licenses/steam-audio"
        COMMAND ${CMAKE_COMMAND} -E copy_if_different "${CMAKE_CURRENT_SOURCE_DIR}/third_party/steam-audio/LICENSE.md" "$<TARGET_FILE_DIR:CanisEngine>/licenses/steam-audio/LICENSE.md"
        COMMAND ${CMAKE_COMMAND} -E copy_if_different "${CANIS_STEAM_AUDIO_ROOT}/THIRDPARTY.md" "$<TARGET_FILE_DIR:CanisEngine>/licenses/steam-audio/THIRDPARTY.md")
    target_compile_definitions(CanisEngine PRIVATE CANIS_STEAM_AUDIO=1)
else()
    target_compile_definitions(CanisEngine PRIVATE CANIS_STEAM_AUDIO=0)
endif()
