option(CANIS_ENABLE_STEAM_INPUT "Enable the native Steam Input provider" OFF)
set(CANIS_STEAMWORKS_SDK "" CACHE PATH "Steamworks SDK root containing public/steam/steam_api.h")
if(CANIS_ENABLE_STEAM_INPUT AND CANIS_PLATFORM_WEB)
    message(FATAL_ERROR "Native Steam Input is unavailable on web builds. Set CANIS_ENABLE_STEAM_INPUT=OFF.")
endif()
if(CANIS_ENABLE_STEAM_INPUT)
    if(NOT EXISTS "${CANIS_STEAMWORKS_SDK}/public/steam/steam_api.h")
        message(FATAL_ERROR "Set CANIS_STEAMWORKS_SDK to your Steamworks SDK directory (containing public/steam/steam_api.h), or disable CANIS_ENABLE_STEAM_INPUT.")
    endif()
    if(WIN32)
        if(CMAKE_SIZEOF_VOID_P EQUAL 8)
            set(STEAM_REDIST "${CANIS_STEAMWORKS_SDK}/redistributable_bin/win64")
            set(STEAM_LIBRARY_NAME steam_api64)
        else()
            set(STEAM_REDIST "${CANIS_STEAMWORKS_SDK}/redistributable_bin")
            set(STEAM_LIBRARY_NAME steam_api)
        endif()
        set(STEAM_RUNTIME "${STEAM_REDIST}/${STEAM_LIBRARY_NAME}.dll")
    elseif(APPLE)
        set(STEAM_REDIST "${CANIS_STEAMWORKS_SDK}/redistributable_bin/osx")
        set(STEAM_LIBRARY_NAME steam_api)
        set(STEAM_RUNTIME "${STEAM_REDIST}/libsteam_api.dylib")
    elseif(UNIX AND CMAKE_SIZEOF_VOID_P EQUAL 8)
        set(STEAM_REDIST "${CANIS_STEAMWORKS_SDK}/redistributable_bin/linux64")
        set(STEAM_LIBRARY_NAME steam_api)
        set(STEAM_RUNTIME "${STEAM_REDIST}/libsteam_api.so")
    else()
        message(FATAL_ERROR "Native Steam Input supports Windows, macOS and 64-bit Linux in this integration.")
    endif()
    find_library(CANIS_STEAM_LIBRARY NAMES ${STEAM_LIBRARY_NAME} PATHS "${STEAM_REDIST}" NO_DEFAULT_PATH REQUIRED)
    if(NOT EXISTS "${STEAM_RUNTIME}")
        message(FATAL_ERROR "Steamworks runtime is missing: ${STEAM_RUNTIME}")
    endif()
    target_include_directories(CanisEngine PRIVATE "${CANIS_STEAMWORKS_SDK}/public")
    target_link_libraries(CanisEngine PRIVATE "${CANIS_STEAM_LIBRARY}")
    target_compile_definitions(CanisEngine PRIVATE CANIS_ENABLE_STEAM_INPUT=1)
    add_custom_command(TARGET CanisEngine POST_BUILD
        COMMAND "${CMAKE_COMMAND}" -E copy_if_different "${STEAM_RUNTIME}" "$<TARGET_FILE_DIR:CanisEngine>" VERBATIM)
else()
    target_compile_definitions(CanisEngine PRIVATE CANIS_ENABLE_STEAM_INPUT=0)
endif()
